name: Publish NuGet package

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-pack-publish:
    name: Build, Pack, and Publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set package version from tag
        id: version
        run: |
          RAW_VERSION="${GITHUB_REF##*/}"       # v0.9.1
          STRIPPED="${RAW_VERSION#v}"           # 0.9.1
          MAJOR_MINOR=$(echo $STRIPPED | cut -d '.' -f1,2)
          FINAL_VERSION="$MAJOR_MINOR.0"
          echo "version=$FINAL_VERSION" >> "$GITHUB_OUTPUT"

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Pack
  run: dotnet pack ./src/Bunny.LibSql.Client/Bunny.LibSql.Client.csproj --configuration Release --no-build --output ./artifacts -p:PackageVersion=${{ steps.version.outputs.version }}

      - name: Publish to NuGet.org
        run: dotnet nuget push ./artifacts/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
